### ISSUE TITLE
Please support Flutter

### ISSUE THREAD

**Issue by MrMoronIV** [Mangopay/cardregistration-ios-kit#12]
Please create an sdk in the Flutter dart language so it's easy to work with mangopay on this highly popular mobile development platform which supports ios and android in one go!

**Comment by Jrbebel** [comment]
Hello, 
news of sdk mangopay for FLUTTER ?

**Comment by nelsou** [comment]
Any update on this issue ? Anyone did it on its side ? :)

**Comment by Jrbebel** [comment]
For now no, I think it should be developed

**Comment by mangomaxoasis** [comment]
Hi @Jrbebel @nelsou @MrMoronIV 
We are actively discussing a Flutter module (as well as a few other similar components)
Unfortunately I can't give a precise indication of a release at this stage
Regards,
max

**Comment by Jrbebel** [comment]
nice @mangomaxoasis :)
I developed a version on android but I am interested in an ios version..

**Comment by rschuil** [comment]
https://github.com/spiritinlife/mangopay-dart-kit

**Comment by mangomaxoasis** [comment]
@rschuil 
Nice !

**Comment by nietsmmar** [comment]
Any news on this issue?

**Comment by AleksandarSavic95** [comment]
Any news? :) 
I see there is this one, but it seems like it's not official
https://pub.dev/packages/mangopay_card

**Comment by layerzzzio** [comment]
Hi,

@mangomaxoasis any news on this one?

I need to use MANGOPAY for my marketplace project. 
I am on the edge of developing a dart package that would be a port of one of the existing versions (java, python etc.).
Before doing so I wanted to know if this is still planned or not?
I wouldn't like to duplicate the work with you guys.

Thank you
Best,

**Comment by rschuil** [comment]
> I am on the edge of developing a dart package that would be a port of one of the existing versions (java, python etc.).

Already did that. https://pub.dev/packages/mangopay_card

**Comment by fredericdelordm** [comment]
Hello @layerzzzio,

For now, Flutter is not planned at least before a year. 

You can go ahead.

Nice job @rschuil

**Comment by layerzzzio** [comment]
> > I am on the edge of developing a dart package that would be a port of one of the existing versions (java, python etc.).
> 
> Already did that. https://pub.dev/packages/mangopay_card

Sorry I was super clear I noticed. I need to use other endpoints from MANGOPAY. Not only the card registration. What I would like to achieve is precisely that: https://docs.mangopay.com/guide/quickstart-marketplace. 

@rschuil your package is super awesome and ideally, I would like to build the rest on top of that. Do you need to use the rest of the endpoints for any of your projects? If so, I would love to work together on that.

Thanks

**Comment by rschuil** [comment]
> I need to use other endpoints from MANGOPAY. Not only the card registration.

iirc those other endpoints should be called from your server, not the client application (or anyone could decompile it, find your api keys, and creates transactions between any wallets)

we use Mangopay in a similar fashion as described in the documentation you linked to. to integrate it into our app, the card registration endpoints were all we needed in Dart.

we've been using the package in production for two years now with no issues.

**Comment by layerzzzio** [comment]
Thank you for the answer 👍 I hate to ask but would there be any possibility to steal 30 min of your time, over Slack or Zoom, to talk about how you implemented such a system in your project (I haven't found any email in your profile). I kinda struggle to find detailed tutorials about that. The MANGOPAY tutorial is great but some questions remain unanswered. It would help tremendously. If not, absolutely no worries 😉

**Comment by rschuil** [comment]
> would there be any possibility to steal 30 min of your time, over Slack or Zoom, 

sure. drop me a mail at info (at) vendora gr
