### ISSUE TITLE
SDK Outdated

### ISSUE THREAD

**Issue by LucianPaun** [Mangopay/cardregistration-ios-kit#13]
Hello.
The existing SDK is outdated, and therefore not functional. The parameters have changed on the official api, and the requests from the SDK always fail with error.
The support staff is telling me that the only way to implement card saving functionality into my iOS app is via the SDK.

For example you **[MAPIClient registerCard]** method is constructing the url for posting card info (https://docs.mangopay.com/endpoints/v2.01/cards#e1042_post-card-info) with the following parameters: 
**cardExpirationDate**
**cardNumber**
**cardCvx**
**data** -> should be **PreregistrationData**
**accessKeyRef** -> should be **AccessKey**

Please try and update this. You can contact me if you have specific code questions.

**Comment by Riwak** [comment]
Hello @LucianPaun, 

The API call to post card info are : 

```
POST : {{CardRegistrationURL}}
{
     accessKeyRef : {{AccessKey}},
     data : {{PreregistrationData}},
     returnURL : "https://your-url",
     cardNumber : "4970101122334422",
     cardExpirationDate : "1020",
     cardCvx : "123"
}
```

**{{CardRegistrationURL}}** & **{{PreregistrationData}}** & **{{AccessKey}}** values are retrieved from the JSON response of Create a Card Registration API call (https://docs.mangopay.com/endpoints/v2.01/cards#e178_create-a-card-registration)

If you have any question don't hesitate.

**Comment by yanis-IOS** [comment]
Hi,
I would like to know if the IOS SDK is still functional or outdated. All the documentation is written in objective-C and the last updates are around 6 years ago. I have tried to use it but some part seems to be deprecated. 
Could you tell me if the SDK is still working?

Thanks in advance.

Best regards
