### ISSUE TITLE
Integration with React Native

### ISSUE THREAD

**Issue by oziomek1** [Mangopay/cardregistration-ios-kit#17]
Hi, I'm looking to integrate the card registration kit with React Native.

Is it currently possible to use this package and the [cardregistration-android-kit](https://github.com/Mangopay/cardregistration-ios-kit) with RN?

Thanks a lot for any info or suggestions.

**Comment by fredericdelordm** [comment]
Hi @oziomek1,

This package is not compatible with react native.

We are planning to add this in the future.
