### ISSUE TITLE
Support for SwiftUI

### ISSUE THREAD

**Issue by SonicxPrime** [Mangopay/cardregistration-ios-kit#18]
Hi everyone,

Is there support for Swift?

Thanks in advance,
Tahina

**Comment by yanis-IOS** [comment]
Hi, 
I would like to know if the SDK currently works with Swift and if there is some updated documentation.

Thanks

**Comment by jidefela-mgp** [comment]
Hello, apologies for the late response here. Please checkout our new Vault SDK (replacing this one) with Swift language support (https://github.com/Mangopay/mangopay-ios-vault-sdk). 

thanks!
