### ISSUE TITLE
Application crash with ios kit

### ISSUE THREAD

**Issue by ivivanov** [Mangopay/cardregistration-ios-kit#5]
### Expected Behavior
Register card through CardRegistrationURL recived from the server

### Actual Behavior
Application crash in registerCard method and ^(NSDictionary response, NSError error) {} is not called

### Code 

self.mangopayClient = [[MPAPIClient alloc] initWithCard:[ServerCommunicationManager sharedInstance].mangopayData];
    
    NSString* cardNumber = _paymentTextField.cardNumber;
    NSString* expDate = [NSString stringWithFormat:@"%d%d", (int)_paymentTextField.expirationMonth, (int)_paymentTextField.expirationYear];
    NSString* cvcData = _paymentTextField.cvc;
    
    [self.mangopayClient appendCardInfo:cardNumber
                     cardExpirationDate:expDate
                                cardCvx:cvcData];
    
    [self.mangopayClient registerCard:^(NSDictionary response, NSError error) {
        if (error) {

        }
        else { // card was VALIDATED
            NSLog(@"VALIDATED %@", response);
        }
    }];
	
	mangopayData:
	{
		accessKey = 1X0m87dmM2LiwFgxPLBJ;
		cardId = "<null>";
		cardRegistrationURL = "https://homologation-webpayment.payline.com/webpayment/getToken";
		cardType = "CB_VISA_MASTERCARD";
		creationDate = 1472386677;
		currency = EUR;
		id = 15467184;
		preregistrationData = "Qi7oou23Q8d9B3xUpjdMuVAfNZHy7zEDRH36z_DvX7AH5Nh7rzFlPmJucFgUmoqHS4wCy-yiraxeE65tmxOe8A";
		registrationData = "<null>";
		resultCode = "<null>";
		status = CREATED;
		tag = DefaultTag;
		userId = 15341402;
    }

###	Config file

`<key>NSAppTransportSecurity</key>
<dict>
  <key>NSAllowsArbitraryLoads</key>
  <false/>
  <key>NSExceptionDomains</key>
  <dict>
    <key>mangopay.com</key>
    <dict>
      <key>NSExceptionAllowsInsecureHTTPLoads</key>
      <true/>
      <key>NSExceptionMinimumTLSVersion</key>
      <string>TLSv1.1</string>
      <key>NSExceptionRequiresForwardSecrecy</key>
      <false/>
      <key>NSIncludesSubdomains</key>
      <true/>
      <key>NSRequiresCertificateTransparency</key>
      <true/>
      <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
      <true/>
      <key>NSThirdPartyExceptionMinimumTLSVersion</key>
      <string>TLSv1.1</string>
      <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
      <true/>
    </dict>
    <key>payline.com</key>
    <dict>
      <key>NSExceptionAllowsInsecureHTTPLoads</key>
      <true/>
      <key>NSExceptionMinimumTLSVersion</key>
      <string>TLSv1.1</string>
      <key>NSExceptionRequiresForwardSecrecy</key>
      <false/>
      <key>NSIncludesSubdomains</key>
      <true/>
      <key>NSRequiresCertificateTransparency</key>
      <true/>
      <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
      <true/>
      <key>NSThirdPartyExceptionMinimumTLSVersion</key>
      <string>TLSv1.1</string>
      <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
      <true/>
    </dict>
    <key>azurewebsites.net</key>
    <dict>
      <key>NSExceptionAllowsInsecureHTTPLoads</key>
      <true/>
      <key>NSExceptionMinimumTLSVersion</key>
      <string>TLSv1.1</string>
      <key>NSExceptionRequiresForwardSecrecy</key>
      <true/>
      <key>NSIncludesSubdomains</key>
      <true/>
      <key>NSRequiresCertificateTransparency</key>
      <true/>
      <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
      <true/>
      <key>NSThirdPartyExceptionMinimumTLSVersion</key>
      <string>TLSv1.1</string>
      <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
      <true/>
    </dict>
  </dict>
</dict>`
	
### Output when issue occurred
no output - app crashes immedietely after calling registerCard

### Other Information
OS version: 934

I also tried to filter some of the data in mangopayData. When i remove the cardRegistrationURL the app does not crash but ofcouse there is an error for missing url.

**Comment by hobailey** [comment]
Hey @ivivanov, thanks for reporting this - we'll take a look and get back to you asap :-)

**Comment by hobailey** [comment]
Quite update - we've been working on this fix and hope to publish it in the next 24hrs :-)

**Comment by victorcampeanu** [comment]
`NSString* expDate = [NSString stringWithFormat:@"%d%d", (int)_paymentTextField.expirationMonth, (int)_paymentTextField.expirationYear];`

casting to int then changing to NSString will not return a string. app crashes when receiving wrong input. update will fix this

**Comment by Nerrazim** [comment]
The line above is fine since both _paymentTextField.expirationYear and _paymentTextField.expirationMonth are NSInteger and _paymentTextField is a custom control. After updating with the new framework app still  crashes also tried with hardcoded expDate @"1219" same issue is reproduced.

**Comment by hobailey** [comment]
Hey @ivivanov, we're really struggling to be able to reproduce your problem :-/ 
Could you try hardcoding the card info to check if you still have the problem?
```
[self.mangopayClient appendCardInfo:@"4970100000000154" cardExpirationDate:@"1016" cardCvx:@"123"];
```

**Comment by ivivanov** [comment]
Small update. We managed to isolate the bug and it seems that .net sdk and ios kit are incompatible. The response from the .net server when we call this method:
         public CardRegistrationDTO Get(string cardRegistrationId);
and the response from your demo app when requesting the same data are different


Response in ios kit demo app:
{
    accessKey = 1X0m87dmM2LiwFgxPLBJ;
    baseURL = "https://api.sandbox.mangopay.com";
    cardPreregistrationId = 15967214;
    cardRegistrationURL = "https://homologation-webpayment.payline.com/webpayment/getToken";
    cardType = "CB_VISA_MASTERCARD";
    clientId = "sdk-unit-tests";
    preregistrationData = "ObMObfSdwRfyE4QClGtUcxTmMdpIz-rcZVkYmZjurphjgzPgxDgRSNd93cZES1qZ7qGR3aNxrLUiPbx-Z--VxQ";
}

Response from .net server:
{
    accessKey = 1X0m87dmM2LiwFgxPLBJ;
    cardId = "<null>";
    cardRegistrationURL = "https://homologation-webpayment.payline.com/webpayment/getToken";
    cardType = "CB_VISA_MASTERCARD";
    creationDate = 1472386677;
    currency = EUR;
    id = 15467184;
    preregistrationData = "Qi7oou23Q8d9B3xUpjdMuVAfNZHy7zEDRH36z_DvX7AH5Nh7rzFlPmJucFgUmoqHS4wCy-yiraxeE65tmxOe8A";
    registrationData = "<null>";
    resultCode = "<null>";
    status = CREATED;
    tag = DefaultTag;
    userId = 15341402;
}

We will build exactly the same response and test it.

**Comment by catacraciun** [comment]
Hello @ivivanov , this is the response sent by the demo server:

https://github.com/codegile/mangopay-card-registration-demo/blob/master/src/main/java/com/mangopay/demo/CardRegistrationResponse.java

**Comment by catacraciun** [comment]
Also, please try importing this kit using CocoaPods (released few days ago),

**Comment by ivivanov** [comment]
it is now working. after creating new response object which is exactly the same as https://github.com/codegile/mangopay-card-registration-demo/blob/master/src/main/java/com/mangopay/demo/CardRegistrationResponse.java
Thanks all for the help.

**Comment by hobailey** [comment]
Great, thanks for the update @ivivanov - glad we got to the bottom of it :-)
