### ISSUE TITLE
Card registration issue

### ISSUE THREAD

**Issue by JDandini** [Mangopay/cardregistration-ios-kit#8]
Hi my friends, I'm having troubles at implementing a complete solution web app and mobile apps (iOS and Android) basically the thing is:
On [your documentation](https://docs.mangopay.com/endpoints/v2.01/cards#e178_create-a-card-registration) you say: 

> Now you have to send to the tokenization server the fields AccessKey, PreregistrationData and the user card details (card number, expiry date and CSC) through a form posted at the CardRegistrationURL.

So we have implement as the documentation says, but now in iOS and Android the app crashes due to  [your sdk for ios](https://github.com/Mangopay/cardregistration-ios-kit)  create a dictionary using the cardAPI.clientId, but following your flow this data does not exist yet. 
![screen shot 2017-06-23 at 3 19 26 pm](https://user-images.githubusercontent.com/2761402/27499158-24f4668a-5828-11e7-981a-b8a493f1df65.png)
Is in the [MPAPIClient.m](https://github.com/Mangopay/cardregistration-ios-kit/blob/master/mangopay/MPAPIClient.m) line 84
Now my question is: what flow we should follow the documentation provided to implement the server side or the documentation to implement on the app?  
We are glad to help on anything you need (like a PR ) to fix one of the sdk (iOS/Android or Java) to accomplish this.

**Comment by JDandini** [comment]
Another thing, tracing the error we have discover that this library conform a request with a url created like: 
```
 baseURL + / v2.01/ + clientId + /CardRegistrations/ + cardPreregistrationId
```

wich in the Server side documentation says the oposite :(

**Comment by zainali201** [comment]
I am facing this since last week. Can you please help me out?

![Screenshot 2020-04-12 at 3 58 57 PM](https://user-images.githubusercontent.com
![Screenshot 2020-04-12 at 3 59 17 PM](https://user-images.githubusercontent.com/36730434/79067144-d7960480-7cd6-11ea-9313-ce04bd9bb3e7.png)
/36730434/79067140-cf3dc980-7cd6-11ea-848a-040812d6b171.png)

**Comment by bwaldvogel** [comment]
@zainali201: Apparently there was a backwards incompatible change in https://homologation-webpayment.payline.com/webpayment/getToken that especially breaks this SDK.

See https://github.com/Mangopay/cardregistration-ios-kit/pull/14 for a fix, especially https://github.com/Mangopay/cardregistration-ios-kit/pull/14/commits/b9decb2ea62f45970be20b497b9951e497d17da4.

**Comment by mangomaxoasis** [comment]
Hi all, 
We are releasing shortly https://github.com/Mangopay/cardregistration-ios-kit/pull/14
In the interim, we'll close this ticket,
Please let us know of any further issues 
Thanks,
max
