### ISSUE TITLE
Exception registering a card

### ISSUE THREAD

**Issue by bellme33** [Mangopay/cardregistration-ios-kit#9]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
*** First throw call stack:
(0x1844fefd8 0x182f60538 0x1843e59a4 0x1843e5814 0x1003caff0 0x1003cab0c 0x1003ca5e0 0x184b081fc 0x184b1fef8 0x184fcd804 0x184f12760 0x184f02b18 0x184fcfba0 0x101101a10 0x10110f2e8 0x101105634 0x101111630 0x10111139c 0x1835bf1d0 0x1835bed7c)
libc++abi.dylib: terminating with uncaught exception of type NSException

This is the code we are using

		let responseObject: [AnyHashable: Any] = ["UserId":"30024628","CardType":"CB_VISA_MASTERCARD","accessKey":"1X0m87dmM2LiwFgxPLBJ","preregistrationData":"_nfGWK2M2AY-H3lgOikqrEC95suymQBt0RPsas6nakYZRvUZ_5QjzL5laIjDKfLJ7qGR3aNxrLUiPbx-Z--VxQ","cardRegistrationURL":"https://homologation-webpayment.payline.com/webpayment/getToken","CardId":"","RegistrationData":"","ResultCode":"","ResultMessage":"","Currency":"GBP","Status":"CREATED","Id":"30065618","Tag":""]
		
			// initiate MPAPIClient with received cardObject
			self.mangopayClient = MPAPIClient(card: responseObject)
			
			// collect card info from the user
			let cardNumber: String = "4706750000000009"
			let cardExpirationMonth: String = "10" // ex: @"10"
			let cardExpirationYear: String = "20" // ex: @"16"
			let cardCvx: String = "123" // ex: @"123"
			self.mangopayClient?.appendCardInfo(cardNumber, cardExpirationDate: "\(cardExpirationMonth)\(cardExpirationYear)", cardCvx: cardCvx)
			
			// register card
			self.mangopayClient?.registerCard({ (response, error) in
				if let error = error {
					print("Error: \(error)")
				} else {
					// card was VALIDATED
					print("VALIDATED \(String(describing: response))")
				}
			})

**Comment by mickaelpois** [comment]
Hi @bellme33,

We will investigate on this issue with a high-priority level.
We will keep you posted on every update about it.

Mickaël

**Comment by mickaelpois** [comment]
Hello @bellme33, 
Your issue cannot be reproduce with xCode 8, xCode 9, and IOS 11.
Could you give us some extra info ? This issue happens everytime you try to register a card with this kit ?

**Comment by bellme33** [comment]
Xcode 8.3.2 and ios10.3

Issue occurs every time unless I get a used to many times error from the server.


On 14 Aug 2017, at 13:35, Mickaël POIS <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @bellme33<https://github.com/bellme33>,
Your issue cannot be reproduce with xCode 8, xCode 9, and IOS 11.
Could you give us some extra info ? This issue happens everytime you try to register a card with this kit ?

**Comment by catacraciun** [comment]
@bellme33 as @andreybog mentioned in the previous comment, I think you are not using the correct CardApi structure that is returned by your backend. Please make sure that you are using the same structure as in https://github.com/Mangopay/cardregistration-ios-kit/blob/master/mangopay/MPCardApiObject.m 

Please feel free to write on this thread if there are issues.
